services:
  - type: web
    name: gearguard-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build && npx prisma generate
    startCommand: npm start
    autoDeploy: true
